### PR TITLE
Update: Bitcoin Core

### PR DESCRIPTION
**Pull request by KenMan79**
Bitcoin core | Bitcoin Core consists of both “full-node” software for fully validating the blockchain as well as a bitcoin wallet.
Bitcoin Core is programmed to decide which blockchain contains a valid transaction. Users of Bitcoin Core only accept transactions for that blockchain, making it the Bitcoin blockchain that everyone else to use.
The open-source project maintains and releases Bitcoin client software called “Bitcoin Core”; which is the descendant of the original Bitcoin software client by Satoshi Nakamoto after publishing the Bitcoin whitepaper.

### CODE REVIEW

**Comment by tesla809** [comment]
AMAZING contribution! You are rocking it @KenMan79 !!! WOOHOO!!! 

@AboldUSER @cryptogoth @skellet0r Do you guys want to review as well and get a contribution in?

**Comment by skellet0r** [comment]
@KenMan79 is on a roll!

**Review by skellet0r — APPROVED** [review]
Great addition! @tesla809  looks like another merge!

**Review by tesla809 — COMMENTED** [review]
Looks good to me! AMAZING STUFF @KenMan79

**Pull request merged**
