### PR TITLE
feat: Added CODE_OF_CONDUCT.md

### LINKED ISSUE #9: Add Code of Conduct
Add code of conduct for meetup and project. 

I have something already I worked on. Any suggestions to it once posted will be appreciated.

### PR DESCRIPTION
**Pull request by tesla809**
resolves #9

### CODE REVIEW

**Comment by tesla809** [comment]
@skellet0r thoughts on the pull request?

**Comment by skellet0r** [comment]
lol @tesla809, now that you've switched to forking and submitting PRs your updates will have to get reviewed. Welcome :hugs: 

Also the code of conduct looks great! Great that you even included the meetup introduction template at the bottom. Really reinforces the idea to build some s#!t and join the conversation.

This looks like a merge to me :+1:

**Comment by tesla809** [comment]
Build some SH*T indeed, LMAO!

Is the location where I place it good? @skellet0r? 

Wasn't sure where to add it in the directory.

**Comment by skellet0r** [comment]
@tesla809 nah perfect, I prefer repositories that put it right in the root directory. Some repos have it in the .github directory, but nobody really looks in there. Right at the root is front and center, can see it right away.

**Pull request merged**
