### PR TITLE
Update: Bull Market

### PR DESCRIPTION
**Pull request by kji304dev**
A bull market is a term that describes the condition of a financial market in which prices are rising or expected to rise. This term usually refers to the stock market, but can be applied to anything traded. Included are bonds, real estate, commodities, and cryptocurrencies.  
Since prices continuously rise and fall during trading, the classification of "bull market" is reserved for extended amounts of time where a large portion of prices are rising.

### CODE REVIEW

**Comment by tesla809** [comment]
WOOHOOO!!!!!!! Congrats @kji304 on your first Pull Request! 

AND ITS MERGED!

**Review by tesla809 — APPROVED** [review]
Looks GREAT! Congrats on your first merged Pull Request.

**Comment by tesla809** [comment]
@kji304 are you part of our slack so that I can give you a shout out?

http://bit.ly/NYC-Blockchain-Devs-Join-Slack

**Comment by kji304dev** [comment]
@tesla809 I just joined the Slack group. Thanks!!

**Pull request merged**
